//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.LogConverterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogConverterService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ParseLogDefaultParser", ReplyAction="http://tempuri.org/IService/ParseLogDefaultParserResponse")]
        string[][] ParseLogDefaultParser(string[] value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ParseLogDefaultParser", ReplyAction="http://tempuri.org/IService/ParseLogDefaultParserResponse")]
        System.Threading.Tasks.Task<string[][]> ParseLogDefaultParserAsync(string[] value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ParseLogCustomParser", ReplyAction="http://tempuri.org/IService/ParseLogCustomParserResponse")]
        string[][] ParseLogCustomParser(string[] value, string Parser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ParseLogCustomParser", ReplyAction="http://tempuri.org/IService/ParseLogCustomParserResponse")]
        System.Threading.Tasks.Task<string[][]> ParseLogCustomParserAsync(string[] value, string Parser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAlarms", ReplyAction="http://tempuri.org/IService/GetAlarmsResponse")]
        string[] GetAlarms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAlarms", ReplyAction="http://tempuri.org/IService/GetAlarmsResponse")]
        System.Threading.Tasks.Task<string[]> GetAlarmsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : TestClient.LogConverterService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<TestClient.LogConverterService.IService>, TestClient.LogConverterService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[][] ParseLogDefaultParser(string[] value) {
            return base.Channel.ParseLogDefaultParser(value);
        }
        
        public System.Threading.Tasks.Task<string[][]> ParseLogDefaultParserAsync(string[] value) {
            return base.Channel.ParseLogDefaultParserAsync(value);
        }
        
        public string[][] ParseLogCustomParser(string[] value, string Parser) {
            return base.Channel.ParseLogCustomParser(value, Parser);
        }
        
        public System.Threading.Tasks.Task<string[][]> ParseLogCustomParserAsync(string[] value, string Parser) {
            return base.Channel.ParseLogCustomParserAsync(value, Parser);
        }
        
        public string[] GetAlarms() {
            return base.Channel.GetAlarms();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAlarmsAsync() {
            return base.Channel.GetAlarmsAsync();
        }
    }
}
